name: Push latest KernelSU
on:
  workflow_dispatch:
  schedule:
    - cron: '16 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        submodules: 'true'
        fetch-depth: 0

    - name: Update Repo and Commit Generated Files
      run: |
        git config --global user.name "Joker-V2"
        git config --global user.email "nipinna0@gmail.com"
        git submodule sync
        git submodule update --init --recursive
        cd $GITHUB_WORKSPACE/KernelSU
        git checkout main
        git pull
        # 假设您的生成步骤在这里
        # make your changes
        cd ..
        git add . # 添加所有更改，包括新文件
        git status # 显示状态以调试目的
        git diff-index --quiet HEAD || git commit -m "KernelSU: Sync with repo and commit generated files" # 如果有更改，则提交它们

    - name: Push Changes
      if: env.ACCESS_TOKEN != ''
      run: |
        git push origin main
      env:
        GIT_AUTHOR_NAME: Joker-V2
        GIT_AUTHOR_EMAIL: nipinna0@gmail.com
        GIT_COMMITTER_NAME: Joker-V2
        GIT_COMMITTER_EMAIL: nipinna0@gmail.com
