name: Build Stable
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Build KernelSU Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup build kernel environment
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libc6-dev clang flex bison libssl-dev bc python3 python2 zip unzip git lld llvm
          mkdir -p $GITHUB_WORKSPACE/KernelSU
          
      - name: Download Proton-clang
        run: |
          cd $GITHUB_WORKSPACE/KernelSU
          git clone https://github.com/kdrag0n/proton-clang.git proton-clang --depth=1
          export PATH="$GITHUB_WORKSPACE/KernelSU/proton-clang/bin:$PATH"
          
      - name: Download kernel source
        run: |
          cd $GITHUB_WORKSPACE/KernelSU
          git clone https://github.com/ldbsmh/kernel_xiaomi_violet.git --depth=1
          
      - name: Integrate KernelSU
        run: |
          cd $GITHUB_WORKSPACE/KernelSU
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          
      - name: Compiling Kernel
        run: |
          cd $GITHUB_WORKSPACE/KernelSU/kernel_xiaomi_violet
          chmod +x build.sh
          ./build.sh
          filename=$(find . -name 'Quick*' -type f -printf '%f\n' | head -n1)
          if [[ -z "$filename" ]]; then
            echo "Error: Kernel build file not found."
            exit 1
          fi
          echo "FILENAME=$filename" >> $GITHUB_ENV
          
      - name: Uploading Kernel
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: QuicksilveR_KernelSU
          path: ${{ github.workspace }}/KernelSU/kernel_xiaomi_violet/${{ env.FILENAME }}
